---
id: Mongo
name: Mongo
full: MongoDB client library
description: >
  Provides an API to ensure that the PECL Mongo extension can be used
  consistently across various Horde packages.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 1.1.1
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
  optional:
    pear:
      pecl.php.net/mongo:
        version: ^1.3
        providesextension: mongo
      pecl.php.net/mongodb:
        version: '*'
        providesextension: mongodb
